### ISSUE TITLE
Severe UI instability with large library

### ISSUE THREAD

**Issue by WhoIsMoloBartell** [MCC321-QC/eMixedNiteMC#28]
**Describe the bug**
An very unstable experience with large libraries (5k+ records), even on a high-end modern rig. Crashes inevitable within a minute.

**To Reproduce**
1. Go to any interactive UI element
2. Click on that element 
3. within a few seconds go to another element and click on it
4. Playnite hangs, then crashes in its entirety. Sometimes when restarting it will warn me that that crash was cause by a plugin, offering safe mode.
5. Throughout all these steps from 2 onwards, up to the crash, the UI responsiveness is very sluggish

**Expected behavior**
Stability

**Screenshots**
N/A, but please advise on what artefacts I can share

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version [e.g. 22]: Latest versions of all plugins, including theme modifier.

**Additional context**
I am sure the problem is with EMixedNightMC as I have disabled all other UI extensions
Disabling ThemeModifier did not improve stability much. 
I tried with eMixedNite and it was faster with the same sized library without the lag preceding the inevitable crash. Overall seemed much more stable than the EMixedNightMC fork.
The crashes seem to happen when any new UI element(s) is/are presented to the user, through basic interaction (changing filters, changing a background, opening a game menu through edit on teh details panel. In fact the only place where it 100% doesn't happen is the Playnite menu itself.
Even when using a small pool of records on screen (through the filter), crashes still happen

I would love to share some log files but I'm not sure where to begin. Any suggestions?

**Comment by MCC321-QC** [comment]
I removed a few DataTriggers, it may help performance. Also be sure to disable the extension BackgroundChanger if you use it because it makes the UI lag. The problem with BackgroundChanger will be fix on next update.

This theme is big and has a lot of components in it, for my library of around 2.5k its still smooth with a modern high-end computer. Let me know if its better in any way after the version 3.6!

**Comment by docHOLO** [comment]
Hello. Have same problem. My playnite loading each details page poorly. I am not using Background Changer extansion. Have 12000 intel and 3060 rtx. Display is 2560x1440. 
Video captured this lag (video recorder not made this loading lag worse):
https://drive.google.com/file/d/1z4_AohgVqhvHSqQqMXxm_M9G5jeYJf-o/view?usp=sharing

**Comment by docHOLO** [comment]
I found one demisolution for this. This theme MUCH easier loading .jpg backgrounds than .png
Using Photoshop Converter tool made this loading issue less noticeable.

**Comment by docHOLO** [comment]
Turned off HLTB - no more lags at all.

**Comment by MCC321-QC** [comment]
> I found one demisolution for this. This theme MUCH easier loading .jpg backgrounds than .png Using Photoshop Converter tool made this loading issue less noticeable.

> Turned off HLTB - no more lags at all.

Thanks for the info @docHOLO! I just tried disabling [HLTB](https://github.com/Lacro59/playnite-howlongtobeat-plugin) and there was a noticeable change in performance so ill try to investigate and see if I can come up with a better way to integrate this plugin. 

For images being in jpeg it sure helps but don't do this for your icon or logo because you will loose any transparency effect. For me I use the plugin [Game Media Processor](https://github.com/azuravian/playnite-gamemediaprocessor) from [azuravian](https://github.com/azuravian) with these settings to resize every images.

| Media Type | Width x Height |
| ---------- | -------------- |
| Cover      |   385 x 545    |
| Background | 1295 x 766     |
| Icon       |   256 x 256    |
| Logo       |   500 x 300    |

Be sure to use the "Resize" panel with both "Keep Aspect Ratio" and "Only Shrink" options enabled. That way it will only downsize any images that's bigger than the Width x Height chosen while keeping the original aspect ratio of the images so its not deformed.

![image_2024-10-20_213222104](https://github.com/user-attachments/assets/a41d93b6-3a67-44af-8ddb-684d66f33f2b)

I then use the plugin [Image Cache Size Saver](https://github.com/darklinkpower/PlayniteExtensionsCollection) from [darklinkpower](https://github.com/darklinkpower) to ease up things a little bit more! I do this after I added a few games but technically you could do this anytime you add a game. I use 2k resolution and the settings for resizing the images does not affect the quality. If you run on 4K, adjust the settings to get better images resolution.

With these done I have a pretty smooth experience using eMixedNiteMC with all the addon it support + some other and having a ~2.5k library, its even better when disabling [HLTB](https://github.com/Lacro59/playnite-howlongtobeat-plugin) and [BackgroundChanger](https://github.com/Lacro59/playnite-backgroundchanger-plugin) but its still ok and not as bad as it is on your [video](https://drive.google.com/file/d/1z4_AohgVqhvHSqQqMXxm_M9G5jeYJf-o/view?usp=sharing) when both are enabled, even with background and cover function enabled in [BackgroundChanger](https://github.com/Lacro59/playnite-backgroundchanger-plugin).

**Comment by MCC321-QC** [comment]
[HLTB](https://github.com/Lacro59/playnite-howlongtobeat-plugin) integration has been improved in [v3.85](https://github.com/MCC321-QC/eMixedNiteMC/commit/fac4b7a84db804905d875cbcd1a8a8b6aa0df1bc)! The plugins left that could maybe be better implemented would be the cover function of [BackgroundChanger](https://github.com/Lacro59/playnite-backgroundchanger-plugin) and the plugin [SuccessStory](https://github.com/Lacro59/playnite-successstory-plugin).
