### ISSUE TITLE
Don't ignore "Vertical spacing to game details" and "Game cover image height" settings

### ISSUE THREAD

**Issue by WildGenius** [MCC321-QC/eMixedNiteMC#41]
### Feature Description

Possibly via a ThemeModifier constant toggle for people who don't want trailers, but do want all the other great integrations.

**Comment by MCC321-QC** [comment]
I ignored those 2 settings because I thought it would be simpler for the user to change these both in grid and details view at the same place and since grid view there was no settings for those I chose to add one for detail view as well so all these setting would be at the same place. 

Can I ask why do you want this?

**Comment by MCC321-QC** [comment]
> To be honest, I didn't even realise these were moved to the theme constants rather than entirely ignored. In my usage, I tend to swap themes every once in a while, and I'd prefer if the native Playnite settings were respected. Maybe default the theme's constants to the native settings?..

Ill see what I can do for this in next update!

**Comment by MCC321-QC** [comment]
This will stay like this for now for the sake of keeping most setting at the same place but this will be a good Idea if we ever need some space in the [ThemeModifier](https://github.com/Lacro59/playnite-thememodifier-plugin) file for the constant menu as the max number of line is 100 and we are at 100 so returning to the default Playnite setting would free us some room.
