### ISSUE TITLE
No more covers in details view. 

### ISSUE THREAD

**Issue by Andei** [MCC321-QC/eMixedNiteMC#43]
### Bug Description

I started Playnite again after a long time and I noticed that no more covers appear in details view. I don't know which update it was because I haven't started Playnite for about half a year.
When I switch to the original eMixedNite theme, the cover appears.

### Screenshots

![grafik](https://github.com/user-attachments/assets/eb81b2ce-c29c-47bb-98ee-c55eb2dbedf4)

**Comment by MCC321-QC** [comment]
This problem has been fixed in [version 3.75](https://github.com/MCC321-QC/eMixedNiteMC/commit/73751b7314770ee404a310837673ed8a91b74dae), the update will release later today or tomorrow! If you want more info on this issue you can refer to [this](https://github.com/MCC321-QC/eMixedNiteMC/issues/33#issuecomment-2424267866).

**Comment by Andei** [comment]
Thank you so much
