### ISSUE TITLE
Everytime I reopen Playnite, the values under Quick Setting wheel get reset

### ISSUE THREAD

**Issue by rohanofgondor** [MCC321-QC/eMixedNiteMC#62]
### Bug Description

Top Part height, Banner and Cover height keeps on getting reset from the values that I set. (check the images attached)

### Screenshots

![Image 1](https://github.com/user-attachments/assets/b6c83709-145d-4248-81a0-61ac1bfb5c8a)
![Image 2](https://github.com/user-attachments/assets/43b83099-c0c5-4cd4-ab9b-2c9b80e2d200)

**Comment by STOPchris1** [comment]
Those settings are only temporary so that you can see what the changes will look like. After you know what settings you want to use, you can into Theme Modifier "edit constants" and make the edits and they will save when you close and reopen. If you go into your addons in the Playnite menu, you can navigate to the location in the screenshot below. There you can select the "Edit Constants" tab. There are a lot of other settings in there that you can play with as well. There is even a reset to default button in-case you want to go back to the default values of a setting. 
![image](https://github.com/user-attachments/assets/cdc482c5-1e9c-49ea-9119-07d3abb548f6)

**Comment by rohanofgondor** [comment]
> Those settings are only temporary so that you can see what the changes will look like. After you know what settings you want to use, you can go into Theme Modifier "edit constants" and make the edits and they will save when you close and reopen. If you go into your addons in the Playnite menu, you can navigate to the location in the screenshot below. There you can select the "Edit Constants" tab. There are a lot of other settings in there that you can play with as well. There is even a reset to default button in-case you want to go back to the default values of a setting. ![image](https://private-user-images.githubusercontent.com/186758401/388646218-cdc482c5-1e9c-49ea-9119-07d3abb548f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNzE3MjIsIm5iZiI6MTczMjI3MTQyMiwicGF0aCI6Ii8xODY3NTg0MDEvMzg4NjQ2MjE4LWNkYzQ4MmM1LTFlOWMtNDllYS05MTE5LTA3ZDNhYmI1NDhmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxMDMwMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDk0MTZkOTZlNGFiMWJjZmNhNGQyYzQ5ZWI5ZTRlZDc2ZDFlNWJjYmJkNDZmNGUwMjFiMzY2Zjc5ZTcyOTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uRqLlA_D1Bf6pD_AlaV7XSPCmxu2-glOVM1LrTZevr8)

Thank you so much for this, and for providing such a thorough breakdown.
