### ISSUE TITLE
Banner for default playnite library

### ISSUE THREAD

**Issue by daephx** [MCC321-QC/eMixedNiteMC#8]
The library banners don't include an image for the default Playnite library which all my emulated games were imported under. 
So, I created one and dropped it into the folder and it seems to have worked.

Care to add it to the project?

![Playnite](https://user-images.githubusercontent.com/36192863/169641837-02552f1e-a144-4b8e-9931-68296647dbbd.png)

---

Edit: I didn't see that this was modeled after [eMixedNite](https://github.com/eminaguil/eMixedNite) and it seems that project has one as well, but it looks a bit lower-res around the icon.

And as an extension of this issue, I don't seem to have any platform specific banners like in the recent screenshots.
e.g. Atari 2600, Gameboy Color, Sony PlayStation 2, PC

**Comment by MCC321-QC** [comment]
I removed the Playnite banner because the Library banners are loaded after the Platform banners so you would not see the Platform banners. 

For example, when you see a Steam banner it means there is also a "PC" platform banner underneath it because its a PC game. <br>(If you added the Platform banners correctly in the Library Manager(CTRL+W) like describe [here](https://github.com/MCC321-QC/eMixedNiteMC#final-step-set-up-your-platform-banners))

As every games you manually add, PC or emulated, goes in the "Playnite Library", you would see the Playnite banner instead of the platform one if it was still in there.

But the way banners a loaded may change soon. The goal would be to included Platform Banners.

**Comment by daephx** [comment]
Man, all too often I glance right over some important info 'right' there in the readme.
Appreciate the info, I wasn't aware of the overwrite problem. To clarify, this is what you mean correct? Where the details box art still says Steam while the library grid are set to PC.

![image](https://user-images.githubusercontent.com/36192863/170476711-5717e76a-9cc6-4ebd-a784-af0b26d6328d.png)

**Comment by MCC321-QC** [comment]
What I mean is that when you see a Library banner, there is in fact the platform banner underneath it too so that is why there is no Playnite Library banner, So you can have both Library banner AND Platform banner at the same time.

For your Library banners not showing in GridList, maybe you have Library banners disable/uncheck in the constant menu of [ThemeModifier](https://github.com/Lacro59/playnite-thememodifier-plugin)?

**Comment by daephx** [comment]
After messing with it and rereading your response, I get what you meant and understand the decision.
I'll likely be leaving the Playnite banner disabled on my setup as well to better differentiate games.

I was initially looking at the big box art not displaying the changes from ThemeModifier's toggle button.
Probably would have been better illustrated using a GIF, but it is a separate issue altogether.

<details>
<summary>Screenshot</summary>

![Playnite DesktopApp_dfjkPzxQNU](https://user-images.githubusercontent.com/36192863/171043698-710609b0-7388-437e-a9e2-04075472bfe1.gif)

</details>

Regardless, thanks for the information and hopefully the future implementation of banner loading works out! Should you reintroduce the Playnite library banner in the future you're free to use the one I posted should you choose to.
